---
- hosts: all  # edit slave node
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Python
      apt:
        name: python3
        state: present
